/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package messageapp;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author medit
 */
public class Screen extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public static DefaultTableModel client_table_model = new DefaultTableModel();
    public static DefaultTableModel room_table_model = new DefaultTableModel();
    public static int chat_box_id = 0;
    public static Map<Integer, Chatbox> IntToRoomChatMap = new HashMap<Integer, Chatbox>();
    public static Map<Integer, Chatbox> IntToClientChatMap = new HashMap<Integer, Chatbox>();
    public static ArrayList<Chatbox> chatboxes = new ArrayList();
    public static Chatbox chosen_chatbox;

    /**
     * deprecated public static ArrayList<DefaultListModel> dlms = new
     * ArrayList(); public static Map<Integer, DefaultListModel> intToRoomDlmMap
     * = new HashMap<Integer, DefaultListModel>(); public static
     * Map<Integer, DefaultListModel> intToClientDlmMap = new
     * HashMap<Integer, DefaultListModel>();
     */
    public Screen() {
        initComponents();

        client_table_model.setColumnIdentifiers(new Object[]{"User Name"});
        user_table.setModel(client_table_model);

        room_table_model.setColumnIdentifiers(new Object[]{"Room Name"});
        room_table.setModel(room_table_model);

        message_screen_panel.setVisible(false);
        message_list.setModel(new DefaultListModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        message_screen_panel = new javax.swing.JPanel();
        back_button = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        message_list = new javax.swing.JList<>();
        stat_current_room_label = new javax.swing.JLabel();
        current_room_label = new javax.swing.JLabel();
        text_field = new javax.swing.JTextField();
        send_button = new javax.swing.JButton();
        start_panel = new javax.swing.JPanel();
        choose_button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        stat_room_label = new javax.swing.JLabel();
        room_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        user_table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        room_table = new javax.swing.JTable();
        create_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back_button.setText("< Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        message_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(message_list);

        stat_current_room_label.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        stat_current_room_label.setText("Current Room :");

        current_room_label.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        send_button.setText("Send");
        send_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout message_screen_panelLayout = new javax.swing.GroupLayout(message_screen_panel);
        message_screen_panel.setLayout(message_screen_panelLayout);
        message_screen_panelLayout.setHorizontalGroup(
            message_screen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(message_screen_panelLayout.createSequentialGroup()
                .addGroup(message_screen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, message_screen_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(text_field))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, message_screen_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, message_screen_panelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(stat_current_room_label, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(current_room_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, message_screen_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(send_button, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(message_screen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(message_screen_panelLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(611, Short.MAX_VALUE)))
        );
        message_screen_panelLayout.setVerticalGroup(
            message_screen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(message_screen_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(message_screen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stat_current_room_label, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(current_room_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(send_button, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(message_screen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, message_screen_panelLayout.createSequentialGroup()
                    .addContainerGap(556, Short.MAX_VALUE)
                    .addComponent(back_button)
                    .addContainerGap()))
        );

        choose_button.setText("Choose ");
        choose_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose_buttonActionPerformed(evt);
            }
        });

        stat_room_label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        stat_room_label.setText("    Rooms : ");

        room_label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        room_label.setText("  Users : ");

        user_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(user_table);

        room_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(room_table);

        create_button.setText("Create Room");
        create_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout start_panelLayout = new javax.swing.GroupLayout(start_panel);
        start_panel.setLayout(start_panelLayout);
        start_panelLayout.setHorizontalGroup(
            start_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(start_panelLayout.createSequentialGroup()
                .addGroup(start_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(create_button, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stat_room_label, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 453, Short.MAX_VALUE)
                .addComponent(choose_button, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(start_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE))
            .addGroup(start_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE))
            .addGroup(start_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(start_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(room_label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(670, Short.MAX_VALUE)))
            .addGroup(start_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(start_panelLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
        );
        start_panelLayout.setVerticalGroup(
            start_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, start_panelLayout.createSequentialGroup()
                .addComponent(stat_room_label, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 533, Short.MAX_VALUE)
                .addGroup(start_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choose_button)
                    .addComponent(create_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(start_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(start_panelLayout.createSequentialGroup()
                    .addGap(330, 330, 330)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
            .addGroup(start_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(start_panelLayout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(316, Short.MAX_VALUE)))
            .addGroup(start_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(start_panelLayout.createSequentialGroup()
                    .addGap(277, 277, 277)
                    .addComponent(room_label, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(260, Short.MAX_VALUE)))
            .addGroup(start_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(start_panelLayout.createSequentialGroup()
                    .addGap(278, 278, 278)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(299, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(start_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(message_screen_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(start_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(message_screen_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choose_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose_buttonActionPerformed

        int row_room = room_table.getSelectedRow();
        int row_user = user_table.getSelectedRow();

        if (row_room != -1) {
            Screen.chosen_chatbox = (Chatbox) room_table.getValueAt(room_table.getSelectedRow(), 0);
            DefaultListModel chosen_model = chosen_chatbox.list_model;
            message_list.setModel(chosen_model);
            if (!Client.joined_rooms.contains(chosen_chatbox.croom.room_id)) {
                text_field.setText("It looks like you are not a member of this group. Please enter a username here to continue :");
                ArrayList<Integer> roo = Client.joined_rooms;
                for (Integer cRoom : roo) {
                    System.out.println("joined rooms "+cRoom+" name "+cRoom);
                }
                System.out.println("chosen box room " + chosen_chatbox.croom.room_id+"  name  "+chosen_chatbox.croom.room_name);
            }
            else{
                text_field.setText("");
                System.out.println("in the room");
            }
                
            message_screen_panel.setVisible(true);
            start_panel.setVisible(false);
        } else if (row_user != -1) {
            Screen.chosen_chatbox = (Chatbox) user_table.getValueAt(user_table.getSelectedRow(), 0);
            message_list.setModel(chosen_chatbox.list_model);
            message_screen_panel.setVisible(true);
            start_panel.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please select a chat from either of the tables", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_choose_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        message_screen_panel.setVisible(false);
        start_panel.setVisible(true);
    }//GEN-LAST:event_back_buttonActionPerformed

    private void send_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_buttonActionPerformed
        if (Client.joined_rooms.contains(chosen_chatbox.croom.room_id)) {
            System.out.println("in the room");
            Message message = new Message(Message.Type.TEXT);
            message.chat_type = Screen.chosen_chatbox.chat_type;
            message.content = text_field.getText();
            message.receiver = Screen.chosen_chatbox.getReceiver();
            message.nickname = Screen.chosen_chatbox.getNickName();
            Client.Send(message);
            Screen.chosen_chatbox.list_model.addElement("You : " + text_field.getText());
            text_field.setText("");
        } else {
            System.out.println("not in the room");
            Message m = new Message(Message.Type.CONN_REQ);
            m.nickname = text_field.getText();
            m.chat_type = Message.Chat_Type.ROOM_MESSAGE;
            m.content = chosen_chatbox.croom;
            Client.Send(m);
        }
    }//GEN-LAST:event_send_buttonActionPerformed

    private void create_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_buttonActionPerformed

    }//GEN-LAST:event_create_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Screen s = new Screen();
                s.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                s.setVisible(true);
            }
        });
    }

    public static Chatbox getChatbox(Message message) {
        if (message.chat_type == Message.Chat_Type.ROOM_MESSAGE) {
            System.out.println("chatbox getchatbx screen method");
            return IntToRoomChatMap.get(((CRoom) message.receiver).room_id);
        }
        return IntToClientChatMap.get(((CClient) message.receiver).client_id);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JButton choose_button;
    private javax.swing.JButton create_button;
    private javax.swing.JLabel current_room_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> message_list;
    private javax.swing.JPanel message_screen_panel;
    private javax.swing.JLabel room_label;
    private javax.swing.JTable room_table;
    private javax.swing.JButton send_button;
    private javax.swing.JPanel start_panel;
    private javax.swing.JLabel stat_current_room_label;
    private javax.swing.JLabel stat_room_label;
    private javax.swing.JTextField text_field;
    private javax.swing.JTable user_table;
    // End of variables declaration//GEN-END:variables
}
